# **PROJETO ANÁLISE DOS DADOS DO COVID 19 NO ESTADO DE SÃO PAULO**

Este projeto analisa os dados dos casos de covid 19 no estado de São Paulo do período de fevereiro de 2020 a setembro de 2021.

Os dados estão disponíveis nos sites:

https://www.seade.gov.br/coronavirus/#

https://github.com/seade-R/dados-covid-sp

https://www.seade.gov.br/

## **Importação dos Dados**

### **Importação de arquivo csv**

In [2]:
# importando as bibliotecas
# pandas - biblioteca responsável por manipular os dados
import numpy as np
import pandas as pd

In [ ]:
# comando do google colab para integração com o google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# carregando as informações do arquivo csv
covid_sp = pd.read_csv('/content/drive/MyDrive/AULAS/dados/dados_covid_sp.csv',
                       sep=';', encoding='utf-8')
# encoding: codificação de caracteres, normalmente utiliza-se
#o iso-8859-1, utf-8, latin-1)

In [ ]:
# visualizando o dados
covid_sp.head(10)

In [ ]:
# contando as linhas e colunas
covid_sp.shape

(614992, 16)

### **Importação de arquivo Excel**

In [ ]:
# carregando informações de um arquivo xlsx
covid_sp2 = pd.read_excel('/content/drive/MyDrive/AULAS/dados/dados_covid_sp2.xlsx')

In [ ]:
# visualizando os dados
covid_sp2.head()

,nome_munic,codigo_ibge,datahora,casos,casos_novos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_pc,obitos_mm7d,letalidade,nome_drs,cod_drs,pop,semana_epidem
0,Adamantina,3500105,2020-02-25,0,0,0.0,0.0,0,0,0.0,0.0,0.0,Marília,5,33894,9
1,Adolfo,3500204,2020-02-25,0,0,0.0,0.0,0,0,0.0,0.0,0.0,São José do Rio Preto,15,3447,9
2,Aguaí,3500303,2020-02-25,0,0,0.0,0.0,0,0,0.0,0.0,0.0,São João da Boa Vista,14,35608,9
3,Águas da Prata,3500402,2020-02-25,0,0,0.0,0.0,0,0,0.0,0.0,0.0,São João da Boa Vista,14,7797,9
4,Águas de Lindóia,3500501,2020-02-25,0,0,0.0,0.0,0,0,0.0,0.0,0.0,Campinas,3,18374,9

In [ ]:
# contanto as linhas e coluna
covid_sp2.shape

(614992, 16)

### **Importação através de uma url**

In [ ]:
# carregando informações de dados a partir de uma url
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

In [ ]:
# criando um array para definir os nomes das colunas
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

In [ ]:
iris = pd.read_csv(url, names=colnames)

In [ ]:
iris.shape

(150, 5)

In [ ]:
iris.head()

   sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
# mostrando todas as colunas do dataframe
iris.columns

Index(['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class'], dtype='object')

In [ ]:
iris.head(10)

   sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [ ]:
# verificando o tipo de dado que está sendo utilizado
type(iris)

pandas.core.frame.DataFrame

In [ ]:
iris.shape

(150, 5)

In [ ]:
# contanto o número de linhas
len(iris.Class)

150

In [ ]:
# acessando uma informação específica
iris['sepal-width'][2]

3.2

### **Datasets das bibliotecas do Python**

https://www.statsmodels.org/stable/datasets/index.html

In [ ]:
# biblioteca de dados para treino do python
import statsmodels.api as sm

In [ ]:
cancer = sm.datasets.cancer.load_pandas().data
cancer.head()

   cancer  population
0     1.0       445.0
1     0.0       559.0
2     3.0       677.0
3     4.0       681.0
4     3.0       746.0

In [ ]:
type(cancer)

pandas.core.frame.DataFrame

In [ ]:
cancer.shape

(301, 2)

https://scikit-learn.org/stable/datasets/toy_dataset.html

In [ ]:
import sklearn

In [ ]:
from sklearn import datasets

In [ ]:
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== ==== ======= ===== ====================\n\n    :Missing Attribute Values: None\n    :Class Distribution: 33.3% for each of 3 classes.\n    :Creator: R.A. Fisher\n    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n    :Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. topic:: References\n\n   - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n     Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n     Mathematical Statistics" (John Wiley, NY, 1950).\n   - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n   - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n     Structure and Classification Rule for Recognition in Partially Exposed\n     Environments".  IEEE Transactions on Pattern Analysis and Machine\n     Intelligence, Vol. PAMI-2, No. 1, 67-71.\n   - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n     on Information Theory, May 1972, 431-433.\n   - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n     conceptual clustering system finds 3 classes in the data.\n   - Many, many more ...',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

In [ ]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

## **Organização dos dados**

### **Renomeando variáveis (colunas)**

In [ ]:
covid_sp.head(3)

,nome_munic,codigo_ibge,datahora,casos,casos_novos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_pc,obitos_mm7d,letalidade,nome_drs,cod_drs,pop,semana_epidem
0,Adamantina,3500105,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",Marília,5,33894,9
1,Adolfo,3500204,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",São José do Rio Preto,15,3447,9
2,Aguaí,3500303,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",São João da Boa Vista,14,35608,9

In [ ]:
covid_sp = covid_sp.rename(columns={'nome_munic': 'municipio'})

In [ ]:
covid_sp.head(3)

In [ ]:
covid_sp.rename(columns={'datahora': 'data'}, inplace=True)

In [ ]:
covid_sp.head(3)

In [ ]:
covid_sp.columns

Index(['municipio', 'codigo_ibge', 'data', 'casos', 'casos_novos', 'casos_pc',
       'casos_mm7d', 'obitos', 'obitos_novos', 'obitos_pc', 'obitos_mm7d',
       'letalidade', 'nome_drs', 'cod_drs', 'pop', 'semana_epidem'],
      dtype='object')

### **Excluindo variáveis (colunas)**

In [ ]:
# Excluir por nome
covid_sp_alterado = covid_sp.drop(columns=['casos_novos'])

In [ ]:
covid_sp_alterado.head(2)

,municipio,codigo_ibge,data,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_pc,obitos_mm7d,letalidade,nome_drs,cod_drs,pop,semana_epidem
0,Adamantina,3500105,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",Marília,5,33894,9
1,Adolfo,3500204,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",São José do Rio Preto,15,3447,9

In [ ]:
covid_sp_alterado.shape

(614992, 15)

In [ ]:
# Excluir por número (axis = 1 irá excluir a coluna)
covid_sp_alterado = covid_sp_alterado.drop(covid_sp_alterado.columns[[1]],axis=1)

In [ ]:
# Excluir mais de uma variável (inplace = True altera a lista sem a necessida de realizar a atribuição novamante)
covid_sp_alterado.drop(columns=['obitos_pc','cod_drs'],inplace=True)

In [ ]:
covid_sp_alterado.head()

,municipio,data,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_mm7d,letalidade,nome_drs,pop,semana_epidem
0,Adamantina,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",Marília,33894,9
1,Adolfo,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",São José do Rio Preto,3447,9
2,Aguaí,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",São João da Boa Vista,35608,9
3,Águas da Prata,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",São João da Boa Vista,7797,9
4,Águas de Lindóia,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",Campinas,18374,9

In [ ]:
covid_sp_alterado.drop(covid_sp_alterado.columns[[9,10]],axis=1, inplace=True)

In [ ]:
covid_sp_alterado.shape

(614992, 10)

### **Criando e alterando valores das colunas (Variáveis)**

In [ ]:
covid_sp_alterado.head(3)

,municipio,data,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_mm7d,letalidade,semana_epidem
0,Adamantina,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9
1,Adolfo,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9
2,Aguaí,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9

In [ ]:
covid_sp_alterado['total'] = covid_sp_alterado['casos']+1

In [ ]:
covid_sp_alterado.head()

,municipio,data,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_mm7d,letalidade,semana_epidem,total
0,Adamantina,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1
1,Adolfo,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1
2,Aguaí,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1
3,Águas da Prata,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1
4,Águas de Lindóia,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1

In [ ]:
covid_sp_alterado.shape

(614992, 11)

In [ ]:
# Criação de uma coluna com índices
lista = list(range(1,374035))
lista

In [ ]:
df = pd.DataFrame(lista,columns=['indice'])
df

In [ ]:
# Juntando dois DataFrames
covid_sp_alterado = pd.concat([covid_sp_alterado,df],axis=1)
covid_sp_alterado.head()

,municipio,data,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_mm7d,letalidade,semana_epidem,total,indice
0,Adamantina,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,1.0
1,Adolfo,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,2.0
2,Aguaí,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,3.0
3,Águas da Prata,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,4.0
4,Águas de Lindóia,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,5.0

### **Contagem de Registros das Variáveis (Colunas)**

In [ ]:
covid_sp_alterado['municipio'].values

array(['Adamantina', 'Adolfo', 'Aguaí', ..., 'Ignorado', 'Ignorado',
       'Ignorado'], dtype=object)

In [ ]:
covid_sp_alterado['semana_epidem'].value_counts().sort_index()

1      9044
2      9044
3      9044
4      9044
5      9044
6      9044
7      9044
8      9044
9     12274
10    13566
11    13566
12    13566
13    13566
14    13566
15    13566
16    13566
17    13566
18    13566
19    13566
20    13566
21    13566
22    13566
23    13566
24    13566
25    13566
26    13566
27    13566
28    13566
29    13566
30    13566
31    13566
32    13566
33    13566
34    13566
35    13566
36    13566
37    13566
38    13566
39    13566
40    10336
41     9044
42     9044
43     9044
44     9044
45     9044
46     9044
47     9044
48     9044
49     9044
50     9044
51     9044
52     9044
53     4522
Name: semana_epidem, dtype: int64

In [ ]:
from collections import Counter
Counter(covid_sp_alterado.semana_epidem)

Counter({9: 12274,
         10: 13566,
         11: 13566,
         12: 13566,
         13: 13566,
         14: 13566,
         15: 13566,
         16: 13566,
         17: 13566,
         18: 13566,
         19: 13566,
         20: 13566,
         21: 13566,
         22: 13566,
         23: 13566,
         24: 13566,
         25: 13566,
         26: 13566,
         27: 13566,
         28: 13566,
         29: 13566,
         30: 13566,
         31: 13566,
         32: 13566,
         33: 13566,
         34: 13566,
         35: 13566,
         36: 13566,
         37: 13566,
         38: 13566,
         39: 13566,
         40: 10336,
         41: 9044,
         42: 9044,
         43: 9044,
         44: 9044,
         45: 9044,
         46: 9044,
         47: 9044,
         48: 9044,
         49: 9044,
         50: 9044,
         51: 9044,
         52: 9044,
         53: 4522,
         1: 9044,
         2: 9044,
         3: 9044,
         4: 9044,
         5: 9044,
         6: 9044,
         7: 9044,
         8: 9044})

In [ ]:
covid_sp_alterado.query('obitos_novos > 50')['municipio'].value_counts()

São Paulo                314
Guarulhos                  9
São Bernardo do Campo      3
Taubaté                    3
Itapetininga               2
Campinas                   1
Sorocaba                   1
Santos                     1
Atibaia                    1
Name: municipio, dtype: int64

### **Selecionar Variáveis (Colunas) por Índices**

In [ ]:
covid_sp_alterado

,municipio,data,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_mm7d,letalidade,semana_epidem,total,indice
0,Adamantina,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,1.0
1,Adolfo,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,2.0
2,Aguaí,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,3.0
3,Águas da Prata,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,4.0
4,Águas de Lindóia,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
614987,Ignorado,2022-09-29,399,"0,00000000000000e+00","-28,000000000000000",5,0,"-1,000000000000000","0,012531328320802004",39,400,NaN
614988,Ignorado,2022-09-30,330,"0,00000000000000e+00","-24,714285714285715",5,0,"-0,285714285714286","0,015151515151515152",39,331,NaN
614989,Ignorado,2022-10-01,204,"0,00000000000000e+00","-63,428571428571431",0,-5,"-1,000000000000000","0,000000000000000000",39,205,NaN
614990,Ignorado,2022-10-02,199,"0,00000000000000e+00","-50,714285714285715",0,0,"-0,714285714285714","0,000000000000000000",40,200,NaN
614991,Ignorado,2022-10-03,199,"0,00000000000000e+00","-45,428571428571431",0,0,"-0,714285714285714","0,000000000000000000",40,200,NaN

In [ ]:
x = covid_sp_alterado.iloc[: , 5:13]
x

,obitos,obitos_novos,obitos_mm7d,letalidade,semana_epidem,total,indice
0,0,0,"0,000000000000000","0,000000000000000000",9,1,1.0
1,0,0,"0,000000000000000","0,000000000000000000",9,1,2.0
2,0,0,"0,000000000000000","0,000000000000000000",9,1,3.0
3,0,0,"0,000000000000000","0,000000000000000000",9,1,4.0
4,0,0,"0,000000000000000","0,000000000000000000",9,1,5.0
...,...,...,...,...,...,...,...
614987,5,0,"-1,000000000000000","0,012531328320802004",39,400,NaN
614988,5,0,"-0,285714285714286","0,015151515151515152",39,331,NaN
614989,0,-5,"-1,000000000000000","0,000000000000000000",39,205,NaN
614990,0,0,"-0,714285714285714","0,000000000000000000",40,200,NaN
614991,0,0,"-0,714285714285714","0,000000000000000000",40,200,NaN

In [ ]:
type(x)

pandas.core.frame.DataFrame

### **Excluindo, Filtrando e Substituindo Registros (Linhas)**

In [ ]:
# Excluindo linhas por índices (valores absolutos)
covid_sp_alterado2 = covid_sp_alterado.drop(covid_sp_alterado.index[[1,3]])
covid_sp_alterado2

,municipio,data,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_mm7d,letalidade,semana_epidem,total,indice
0,Adamantina,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,1.0
2,Aguaí,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,3.0
4,Águas de Lindóia,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,5.0
5,Águas de Santa Bárbara,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,6.0
6,Águas de São Pedro,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...
614987,Ignorado,2022-09-29,399,"0,00000000000000e+00","-28,000000000000000",5,0,"-1,000000000000000","0,012531328320802004",39,400,NaN
614988,Ignorado,2022-09-30,330,"0,00000000000000e+00","-24,714285714285715",5,0,"-0,285714285714286","0,015151515151515152",39,331,NaN
614989,Ignorado,2022-10-01,204,"0,00000000000000e+00","-63,428571428571431",0,-5,"-1,000000000000000","0,000000000000000000",39,205,NaN
614990,Ignorado,2022-10-02,199,"0,00000000000000e+00","-50,714285714285715",0,0,"-0,714285714285714","0,000000000000000000",40,200,NaN
614991,Ignorado,2022-10-03,199,"0,00000000000000e+00","-45,428571428571431",0,0,"-0,714285714285714","0,000000000000000000",40,200,NaN

In [ ]:
# Excluindo linhas por índices (intervalo de valores)
covid_sp_alterado2 = covid_sp_alterado2.drop(covid_sp_alterado.index[4:7])
covid_sp_alterado2

,municipio,data,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_mm7d,letalidade,semana_epidem,total,indice
0,Adamantina,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,1.0
2,Aguaí,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,3.0
7,Agudos,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,8.0
8,Alambari,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,9.0
9,Alfredo Marcondes,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...
614987,Ignorado,2022-09-29,399,"0,00000000000000e+00","-28,000000000000000",5,0,"-1,000000000000000","0,012531328320802004",39,400,NaN
614988,Ignorado,2022-09-30,330,"0,00000000000000e+00","-24,714285714285715",5,0,"-0,285714285714286","0,015151515151515152",39,331,NaN
614989,Ignorado,2022-10-01,204,"0,00000000000000e+00","-63,428571428571431",0,-5,"-1,000000000000000","0,000000000000000000",39,205,NaN
614990,Ignorado,2022-10-02,199,"0,00000000000000e+00","-50,714285714285715",0,0,"-0,714285714285714","0,000000000000000000",40,200,NaN
614991,Ignorado,2022-10-03,199,"0,00000000000000e+00","-45,428571428571431",0,0,"-0,714285714285714","0,000000000000000000",40,200,NaN

In [ ]:
# Reordenar (resetar) índices
covid_sp_alterado2 = covid_sp_alterado2.reset_index(drop=True) # drop é para excluir índice anterior
covid_sp_alterado2

,municipio,data,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_mm7d,letalidade,semana_epidem,total,indice
0,Adamantina,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,1.0
1,Aguaí,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,3.0
2,Agudos,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,8.0
3,Alambari,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,9.0
4,Alfredo Marcondes,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...
614982,Ignorado,2022-09-29,399,"0,00000000000000e+00","-28,000000000000000",5,0,"-1,000000000000000","0,012531328320802004",39,400,NaN
614983,Ignorado,2022-09-30,330,"0,00000000000000e+00","-24,714285714285715",5,0,"-0,285714285714286","0,015151515151515152",39,331,NaN
614984,Ignorado,2022-10-01,204,"0,00000000000000e+00","-63,428571428571431",0,-5,"-1,000000000000000","0,000000000000000000",39,205,NaN
614985,Ignorado,2022-10-02,199,"0,00000000000000e+00","-50,714285714285715",0,0,"-0,714285714285714","0,000000000000000000",40,200,NaN
614986,Ignorado,2022-10-03,199,"0,00000000000000e+00","-45,428571428571431",0,0,"-0,714285714285714","0,000000000000000000",40,200,NaN

In [ ]:
ignorado = covid_sp_alterado.loc[covid_sp_alterado.municipio == 'Ignorado']
ignorado

,municipio,data,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_mm7d,letalidade,semana_epidem,total,indice
614040,Ignorado,2020-02-25,-1,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,0,NaN
614041,Ignorado,2020-02-26,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,NaN
614042,Ignorado,2020-02-27,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,NaN
614043,Ignorado,2020-02-28,-1,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,0,NaN
614044,Ignorado,2020-02-29,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
614987,Ignorado,2022-09-29,399,"0,00000000000000e+00","-28,000000000000000",5,0,"-1,000000000000000","0,012531328320802004",39,400,NaN
614988,Ignorado,2022-09-30,330,"0,00000000000000e+00","-24,714285714285715",5,0,"-0,285714285714286","0,015151515151515152",39,331,NaN
614989,Ignorado,2022-10-01,204,"0,00000000000000e+00","-63,428571428571431",0,-5,"-1,000000000000000","0,000000000000000000",39,205,NaN
614990,Ignorado,2022-10-02,199,"0,00000000000000e+00","-50,714285714285715",0,0,"-0,714285714285714","0,000000000000000000",40,200,NaN
614991,Ignorado,2022-10-03,199,"0,00000000000000e+00","-45,428571428571431",0,0,"-0,714285714285714","0,000000000000000000",40,200,NaN

In [ ]:
ignorado.shape

(952, 12)

In [ ]:
covid_sp_alterado = covid_sp_alterado.loc[covid_sp_alterado.municipio != 'Ignorado']
covid_sp_alterado

,municipio,data,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_mm7d,letalidade,semana_epidem,total,indice
0,Adamantina,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,1.0
1,Adolfo,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,2.0
2,Aguaí,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,3.0
3,Águas da Prata,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,4.0
4,Águas de Lindóia,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
614035,Votorantim,2022-10-03,12539,"1,04645146214448e+04","0,000000000000000",572,0,"0,000000000000000","0,045617672860674696",40,12540,NaN
614036,Votuporanga,2022-10-03,21262,"2,31713164777681e+04","27,857142857142858",508,0,"0,000000000000000","0,023892390179663249",40,21263,NaN
614037,Zacarias,2022-10-03,279,"1,08984375000000e+04","0,000000000000000",12,0,"0,000000000000000","0,043010752688172046",40,280,NaN
614038,Chavantes,2022-10-03,2697,"2,20649595025771e+04","0,142857142857143",60,0,"0,000000000000000","0,022246941045606230",40,2698,NaN
614039,Estiva Gerbi,2022-10-03,1195,"1,07861720371875e+04","0,000000000000000",36,0,"0,000000000000000","0,030125523012552301",40,1196,NaN

In [ ]:
guarulhos = covid_sp_alterado.loc[covid_sp_alterado.municipio == 'Guarulhos']
guarulhos

,municipio,data,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_mm7d,letalidade,semana_epidem,total,indice
212,Guarulhos,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,213.0
857,Guarulhos,2020-02-26,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,858.0
1502,Guarulhos,2020-02-27,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,1503.0
2147,Guarulhos,2020-02-28,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,2148.0
2792,Guarulhos,2020-02-29,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,2793.0
...,...,...,...,...,...,...,...,...,...,...,...,...
611027,Guarulhos,2022-09-29,84405,"6,24632291724482e+03","4,000000000000000",5520,0,"0,428571428571429","0,065398969255375861",39,84406,NaN
611672,Guarulhos,2022-09-30,84408,"6,24654492978853e+03","3,428571428571428",5520,0,"0,000000000000000","0,065396644867785042",39,84409,NaN
612317,Guarulhos,2022-10-01,84413,"6,24691495069471e+03","4,142857142857143",5521,1,"0,142857142857143","0,065404617772144097",39,84414,NaN
612962,Guarulhos,2022-10-02,84413,"6,24691495069471e+03","3,857142857142857",5524,3,"0,571428571428571","0,065440157321739537",40,84414,NaN
613607,Guarulhos,2022-10-03,84414,"6,24698895487595e+03","3,714285714285714",5524,0,"0,571428571428571","0,065439382093017751",40,84415,NaN

In [ ]:
guarulhos.drop(columns=['data','municipio'],inplace=True)
guarulhos.head()

<ipython-input-78-d4bedae52321>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  guarulhos.drop(columns=['data','municipio'],inplace=True)

,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_mm7d,letalidade,semana_epidem,total,indice
212,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,213.0
857,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,858.0
1502,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,1503.0
2147,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,2148.0
2792,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",9,1,2793.0

In [ ]:
guarulhos['semana_epidem']=guarulhos['semana_epidem'].replace({9:'nove', 10: 'dez'})
guarulhos.head(10)

<ipython-input-79-1775dbe23416>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  guarulhos['semana_epidem']=guarulhos['semana_epidem'].replace({9:'nove', 10: 'dez'})

,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_mm7d,letalidade,semana_epidem,total,indice
212,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,213.0
857,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,858.0
1502,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,1503.0
2147,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,2148.0
2792,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,2793.0
3437,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",dez,1,3438.0
4082,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",dez,1,4083.0
4727,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",dez,1,4728.0
5372,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",dez,1,5373.0
6017,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",dez,1,6018.0

In [ ]:
guarulhos['semana_epidem']=guarulhos['semana_epidem'].replace([11,12,13],['onze','doze','treze'])
guarulhos.head(30)

<ipython-input-80-833e91623bb8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  guarulhos['semana_epidem']=guarulhos['semana_epidem'].replace([11,12,13],['onze','doze','treze'])

,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_mm7d,letalidade,semana_epidem,total,indice
212,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,213.0
857,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,858.0
1502,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,1503.0
2147,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,2148.0
2792,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,2793.0
3437,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",dez,1,3438.0
4082,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",dez,1,4083.0
4727,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",dez,1,4728.0
5372,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",dez,1,5373.0
6017,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",dez,1,6018.0
6662,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",dez,1,6663.0
7307,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",dez,1,7308.0
7952,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",onze,1,7953.0
8597,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",onze,1,8598.0
9242,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",onze,1,9243.0
9887,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",onze,1,9888.0
10532,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",onze,1,10533.0
11177,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",onze,1,11178.0
11822,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",onze,1,11823.0
12467,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",doze,1,12468.0
13112,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",doze,1,13113.0
13757,1,"7,40041812362398e-02","0,142857142857143",0,0,"0,000000000000000","0,000000000000000000",doze,2,13758.0
14402,1,"7,40041812362398e-02","0,142857142857143",0,0,"0,000000000000000","0,000000000000000000",doze,2,14403.0
15047,1,"7,40041812362398e-02","0,142857142857143",0,0,"0,000000000000000","0,000000000000000000",doze,2,15048.0
15692,1,"7,40041812362398e-02","0,142857142857143",0,0,"0,000000000000000","0,000000000000000000",doze,2,15693.0
16337,1,"7,40041812362398e-02","0,142857142857143",0,0,"0,000000000000000","0,000000000000000000",doze,2,16338.0
16982,1,"7,40041812362398e-02","0,142857142857143",0,0,"0,000000000000000","0,000000000000000000",treze,2,16983.0
17627,1,"7,40041812362398e-02","0,142857142857143",0,0,"0,000000000000000","0,000000000000000000",treze,2,17628.0
18272,1,"7,40041812362398e-02","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",treze,2,18273.0
18917,5,"3,70020906181199e-01","0,571428571428571",1,1,"0,142857142857143","0,200000000000000011",treze,6,18918.0

In [ ]:
guarulhos['casos_pc'] = guarulhos['casos_pc'].apply(lambda x: x.replace(',','.'))
guarulhos

<ipython-input-81-0e43ef74225c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  guarulhos['casos_pc'] = guarulhos['casos_pc'].apply(lambda x: x.replace(',','.'))

,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_mm7d,letalidade,semana_epidem,total,indice
212,0,0.00000000000000e+00,"0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,213.0
857,0,0.00000000000000e+00,"0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,858.0
1502,0,0.00000000000000e+00,"0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,1503.0
2147,0,0.00000000000000e+00,"0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,2148.0
2792,0,0.00000000000000e+00,"0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,2793.0
...,...,...,...,...,...,...,...,...,...,...
611027,84405,6.24632291724482e+03,"4,000000000000000",5520,0,"0,428571428571429","0,065398969255375861",39,84406,NaN
611672,84408,6.24654492978853e+03,"3,428571428571428",5520,0,"0,000000000000000","0,065396644867785042",39,84409,NaN
612317,84413,6.24691495069471e+03,"4,142857142857143",5521,1,"0,142857142857143","0,065404617772144097",39,84414,NaN
612962,84413,6.24691495069471e+03,"3,857142857142857",5524,3,"0,571428571428571","0,065440157321739537",40,84414,NaN
613607,84414,6.24698895487595e+03,"3,714285714285714",5524,0,"0,571428571428571","0,065439382093017751",40,84415,NaN

In [ ]:
guarulhos.shape

(952, 10)

In [ ]:
# Criar coluna com datas
import datetime

In [ ]:
data = np.array('2020-02-25', dtype = np.datetime64())
data

array('2020-02-25', dtype='datetime64[D]')

In [ ]:
data = data + np.arange(579)
data

array(['2020-02-25', '2020-02-26', '2020-02-27', '2020-02-28',
       '2020-02-29', '2020-03-01', '2020-03-02', '2020-03-03',
       '2020-03-04', '2020-03-05', '2020-03-06', '2020-03-07',
       '2020-03-08', '2020-03-09', '2020-03-10', '2020-03-11',
       '2020-03-12', '2020-03-13', '2020-03-14', '2020-03-15',
       '2020-03-16', '2020-03-17', '2020-03-18', '2020-03-19',
       '2020-03-20', '2020-03-21', '2020-03-22', '2020-03-23',
       '2020-03-24', '2020-03-25', '2020-03-26', '2020-03-27',
       '2020-03-28', '2020-03-29', '2020-03-30', '2020-03-31',
       '2020-04-01', '2020-04-02', '2020-04-03', '2020-04-04',
       '2020-04-05', '2020-04-06', '2020-04-07', '2020-04-08',
       '2020-04-09', '2020-04-10', '2020-04-11', '2020-04-12',
       '2020-04-13', '2020-04-14', '2020-04-15', '2020-04-16',
       '2020-04-17', '2020-04-18', '2020-04-19', '2020-04-20',
       '2020-04-21', '2020-04-22', '2020-04-23', '2020-04-24',
       '2020-04-25', '2020-04-26', '2020-04-27', '2020-04-28',
       '2020-04-29', '2020-04-30', '2020-05-01', '2020-05-02',
       '2020-05-03', '2020-05-04', '2020-05-05', '2020-05-06',
       '2020-05-07', '2020-05-08', '2020-05-09', '2020-05-10',
       '2020-05-11', '2020-05-12', '2020-05-13', '2020-05-14',
       '2020-05-15', '2020-05-16', '2020-05-17', '2020-05-18',
       '2020-05-19', '2020-05-20', '2020-05-21', '2020-05-22',
       '2020-05-23', '2020-05-24', '2020-05-25', '2020-05-26',
       '2020-05-27', '2020-05-28', '2020-05-29', '2020-05-30',
       '2020-05-31', '2020-06-01', '2020-06-02', '2020-06-03',
       '2020-06-04', '2020-06-05', '2020-06-06', '2020-06-07',
       '2020-06-08', '2020-06-09', '2020-06-10', '2020-06-11',
       '2020-06-12', '2020-06-13', '2020-06-14', '2020-06-15',
       '2020-06-16', '2020-06-17', '2020-06-18', '2020-06-19',
       '2020-06-20', '2020-06-21', '2020-06-22', '2020-06-23',
       '2020-06-24', '2020-06-25', '2020-06-26', '2020-06-27',
       '2020-06-28', '2020-06-29', '2020-06-30', '2020-07-01',
       '2020-07-02', '2020-07-03', '2020-07-04', '2020-07-05',
       '2020-07-06', '2020-07-07', '2020-07-08', '2020-07-09',
       '2020-07-10', '2020-07-11', '2020-07-12', '2020-07-13',
       '2020-07-14', '2020-07-15', '2020-07-16', '2020-07-17',
       '2020-07-18', '2020-07-19', '2020-07-20', '2020-07-21',
       '2020-07-22', '2020-07-23', '2020-07-24', '2020-07-25',
       '2020-07-26', '2020-07-27', '2020-07-28', '2020-07-29',
       '2020-07-30', '2020-07-31', '2020-08-01', '2020-08-02',
       '2020-08-03', '2020-08-04', '2020-08-05', '2020-08-06',
       '2020-08-07', '2020-08-08', '2020-08-09', '2020-08-10',
       '2020-08-11', '2020-08-12', '2020-08-13', '2020-08-14',
       '2020-08-15', '2020-08-16', '2020-08-17', '2020-08-18',
       '2020-08-19', '2020-08-20', '2020-08-21', '2020-08-22',
       '2020-08-23', '2020-08-24', '2020-08-25', '2020-08-26',
       '2020-08-27', '2020-08-28', '2020-08-29', '2020-08-30',
       '2020-08-31', '2020-09-01', '2020-09-02', '2020-09-03',
       '2020-09-04', '2020-09-05', '2020-09-06', '2020-09-07',
       '2020-09-08', '2020-09-09', '2020-09-10', '2020-09-11',
       '2020-09-12', '2020-09-13', '2020-09-14', '2020-09-15',
       '2020-09-16', '2020-09-17', '2020-09-18', '2020-09-19',
       '2020-09-20', '2020-09-21', '2020-09-22', '2020-09-23',
       '2020-09-24', '2020-09-25', '2020-09-26', '2020-09-27',
       '2020-09-28', '2020-09-29', '2020-09-30', '2020-10-01',
       '2020-10-02', '2020-10-03', '2020-10-04', '2020-10-05',
       '2020-10-06', '2020-10-07', '2020-10-08', '2020-10-09',
       '2020-10-10', '2020-10-11', '2020-10-12', '2020-10-13',
       '2020-10-14', '2020-10-15', '2020-10-16', '2020-10-17',
       '2020-10-18', '2020-10-19', '2020-10-20', '2020-10-21',
       '2020-10-22', '2020-10-23', '2020-10-24', '2020-10-25',
       '2020-10-26', '2020-10-27', '2020-10-28', '2020-10-29',
       '2020-10-30', '2020-10-31', '2020-11-01', '2020-11-02',
       '2020-11-03', '2020-11-04', '2020-11-05', '2020-11-06',
       '2020-11-07', '2020-11-08', '2020-11-09', '2020-11-10',
       '2020-11-11', '2020-11-12', '2020-11-13', '2020-11-14',
       '2020-11-15', '2020-11-16', '2020-11-17', '2020-11-18',
       '2020-11-19', '2020-11-20', '2020-11-21', '2020-11-22',
       '2020-11-23', '2020-11-24', '2020-11-25', '2020-11-26',
       '2020-11-27', '2020-11-28', '2020-11-29', '2020-11-30',
       '2020-12-01', '2020-12-02', '2020-12-03', '2020-12-04',
       '2020-12-05', '2020-12-06', '2020-12-07', '2020-12-08',
       '2020-12-09', '2020-12-10', '2020-12-11', '2020-12-12',
       '2020-12-13', '2020-12-14', '2020-12-15', '2020-12-16',
       '2020-12-17', '2020-12-18', '2020-12-19', '2020-12-20',
       '2020-12-21', '2020-12-22', '2020-12-23', '2020-12-24',
       '2020-12-25', '2020-12-26', '2020-12-27', '2020-12-28',
       '2020-12-29', '2020-12-30', '2020-12-31', '2021-01-01',
       '2021-01-02', '2021-01-03', '2021-01-04', '2021-01-05',
       '2021-01-06', '2021-01-07', '2021-01-08', '2021-01-09',
       '2021-01-10', '2021-01-11', '2021-01-12', '2021-01-13',
       '2021-01-14', '2021-01-15', '2021-01-16', '2021-01-17',
       '2021-01-18', '2021-01-19', '2021-01-20', '2021-01-21',
       '2021-01-22', '2021-01-23', '2021-01-24', '2021-01-25',
       '2021-01-26', '2021-01-27', '2021-01-28', '2021-01-29',
       '2021-01-30', '2021-01-31', '2021-02-01', '2021-02-02',
       '2021-02-03', '2021-02-04', '2021-02-05', '2021-02-06',
       '2021-02-07', '2021-02-08', '2021-02-09', '2021-02-10',
       '2021-02-11', '2021-02-12', '2021-02-13', '2021-02-14',
       '2021-02-15', '2021-02-16', '2021-02-17', '2021-02-18',
       '2021-02-19', '2021-02-20', '2021-02-21', '2021-02-22',
       '2021-02-23', '2021-02-24', '2021-02-25', '2021-02-26',
       '2021-02-27', '2021-02-28', '2021-03-01', '2021-03-02',
       '2021-03-03', '2021-03-04', '2021-03-05', '2021-03-06',
       '2021-03-07', '2021-03-08', '2021-03-09', '2021-03-10',
       '2021-03-11', '2021-03-12', '2021-03-13', '2021-03-14',
       '2021-03-15', '2021-03-16', '2021-03-17', '2021-03-18',
       '2021-03-19', '2021-03-20', '2021-03-21', '2021-03-22',
       '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
       '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
       '2021-03-31', '2021-04-01', '2021-04-02', '2021-04-03',
       '2021-04-04', '2021-04-05', '2021-04-06', '2021-04-07',
       '2021-04-08', '2021-04-09', '2021-04-10', '2021-04-11',
       '2021-04-12', '2021-04-13', '2021-04-14', '2021-04-15',
       '2021-04-16', '2021-04-17', '2021-04-18', '2021-04-19',
       '2021-04-20', '2021-04-21', '2021-04-22', '2021-04-23',
       '2021-04-24', '2021-04-25', '2021-04-26', '2021-04-27',
       '2021-04-28', '2021-04-29', '2021-04-30', '2021-05-01',
       '2021-05-02', '2021-05-03', '2021-05-04', '2021-05-05',
       '2021-05-06', '2021-05-07', '2021-05-08', '2021-05-09',
       '2021-05-10', '2021-05-11', '2021-05-12', '2021-05-13',
       '2021-05-14', '2021-05-15', '2021-05-16', '2021-05-17',
       '2021-05-18', '2021-05-19', '2021-05-20', '2021-05-21',
       '2021-05-22', '2021-05-23', '2021-05-24', '2021-05-25',
       '2021-05-26', '2021-05-27', '2021-05-28', '2021-05-29',
       '2021-05-30', '2021-05-31', '2021-06-01', '2021-06-02',
       '2021-06-03', '2021-06-04', '2021-06-05', '2021-06-06',
       '2021-06-07', '2021-06-08', '2021-06-09', '2021-06-10',
       '2021-06-11', '2021-06-12', '2021-06-13', '2021-06-14',
       '2021-06-15', '2021-06-16', '2021-06-17', '2021-06-18',
       '2021-06-19', '2021-06-20', '2021-06-21', '2021-06-22',
       '2021-06-23', '2021-06-24', '2021-06-25', '2021-06-26',
       '2021-06-27', '2021-06-28', '2021-06-29', '2021-06-30',
       '2021-07-01', '2021-07-02', '2021-07-03', '2021-07-04',
       '2021-07-05', '2021-07-06', '2021-07-07', '2021-07-08',
       '2021-07-09', '2021-07-10', '2021-07-11', '2021-07-12',
       '2021-07-13', '2021-07-14', '2021-07-15', '2021-07-16',
       '2021-07-17', '2021-07-18', '2021-07-19', '2021-07-20',
       '2021-07-21', '2021-07-22', '2021-07-23', '2021-07-24',
       '2021-07-25', '2021-07-26', '2021-07-27', '2021-07-28',
       '2021-07-29', '2021-07-30', '2021-07-31', '2021-08-01',
       '2021-08-02', '2021-08-03', '2021-08-04', '2021-08-05',
       '2021-08-06', '2021-08-07', '2021-08-08', '2021-08-09',
       '2021-08-10', '2021-08-11', '2021-08-12', '2021-08-13',
       '2021-08-14', '2021-08-15', '2021-08-16', '2021-08-17',
       '2021-08-18', '2021-08-19', '2021-08-20', '2021-08-21',
       '2021-08-22', '2021-08-23', '2021-08-24', '2021-08-25',
       '2021-08-26', '2021-08-27', '2021-08-28', '2021-08-29',
       '2021-08-30', '2021-08-31', '2021-09-01', '2021-09-02',
       '2021-09-03', '2021-09-04', '2021-09-05', '2021-09-06',
       '2021-09-07', '2021-09-08', '2021-09-09', '2021-09-10',
       '2021-09-11', '2021-09-12', '2021-09-13', '2021-09-14',
       '2021-09-15', '2021-09-16', '2021-09-17', '2021-09-18',
       '2021-09-19', '2021-09-20', '2021-09-21', '2021-09-22',
       '2021-09-23', '2021-09-24', '2021-09-25'], dtype='datetime64[D]')

In [ ]:
data = pd.DataFrame(data)
data

             0
0   2020-02-25
1   2020-02-26
2   2020-02-27
3   2020-02-28
4   2020-02-29
..         ...
574 2021-09-21
575 2021-09-22
576 2021-09-23
577 2021-09-24
578 2021-09-25

[579 rows x 1 columns]

In [ ]:
data.columns = ['data']
data.head()

        data
0 2020-02-25
1 2020-02-26
2 2020-02-27
3 2020-02-28
4 2020-02-29

In [ ]:
data = data.append(['2020-02-24','2023-02-25'])
data

df_final = df_final.append({'Posição' : '17º +1 CSA',	'J' : 37,	'E' : 37,	'D' : 37,	'GP' : 37,
                            'CA' : 37,	'p' : 35,	'v' : 37,	'gc' : 37,	'sg' : 37},
                           ignore_index=True)

<ipython-input-103-3a90ddb6ee34>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(['2020-02-24','2023-02-25'])

          data           0
0   2020-02-25         NaN
1   2020-02-26         NaN
2   2020-02-27         NaN
3   2020-02-28         NaN
4   2020-02-29         NaN
..         ...         ...
576 2021-09-23         NaN
577 2021-09-24         NaN
578 2021-09-25         NaN
0          NaT  2020-02-24
1          NaT  2023-02-25

[581 rows x 2 columns]

In [ ]:
guarulhos2 = pd.concat([data,guarulhos],axis=1)
guarulhos2.head()

,data,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_mm7d,letalidade,semana_epidem,total,indice
0,2020-02-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-02-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-02-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Reordenar (resetar) índices
guarulhos = guarulhos.reset_index(drop=True) # drop é para excluir índice anterior
guarulhos

,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_mm7d,letalidade,semana_epidem,total,indice
0,0,0.00000000000000e+00,"0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,213.0
1,0,0.00000000000000e+00,"0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,858.0
2,0,0.00000000000000e+00,"0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,1503.0
3,0,0.00000000000000e+00,"0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,2148.0
4,0,0.00000000000000e+00,"0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,2793.0
...,...,...,...,...,...,...,...,...,...,...
947,84405,6.24632291724482e+03,"4,000000000000000",5520,0,"0,428571428571429","0,065398969255375861",39,84406,NaN
948,84408,6.24654492978853e+03,"3,428571428571428",5520,0,"0,000000000000000","0,065396644867785042",39,84409,NaN
949,84413,6.24691495069471e+03,"4,142857142857143",5521,1,"0,142857142857143","0,065404617772144097",39,84414,NaN
950,84413,6.24691495069471e+03,"3,857142857142857",5524,3,"0,571428571428571","0,065440157321739537",40,84414,NaN
951,84414,6.24698895487595e+03,"3,714285714285714",5524,0,"0,571428571428571","0,065439382093017751",40,84415,NaN

In [ ]:
guarulhos2 = pd.concat([data,guarulhos],axis=1)
guarulhos2.head()

,data,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_mm7d,letalidade,semana_epidem,total,indice
0,2020-02-25,0,0.00000000000000e+00,"0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,213.0
1,2020-02-26,0,0.00000000000000e+00,"0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,858.0
2,2020-02-27,0,0.00000000000000e+00,"0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,1503.0
3,2020-02-28,0,0.00000000000000e+00,"0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,2148.0
4,2020-02-29,0,0.00000000000000e+00,"0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",nove,1,2793.0

In [ ]:
guarulhos2.shape

(952, 11)

### **Valores Missing (NAN)**

In [ ]:
# RELAÇÃO DA QUANTIDADE
covid_sp_alterado.isnull().sum()

municipio             0
data                  0
casos                 0
casos_pc              0
casos_mm7d            0
obitos                0
obitos_novos          0
obitos_mm7d           0
letalidade            0
semana_epidem         0
total                 0
indice           240006
dtype: int64

In [ ]:
covid_sp_alterado['casos'].isnull().sum()

0

In [ ]:
# RELAÇÃO DA QUANTIDADE
covid_sp.isnull().sum()

municipio          0
codigo_ibge        0
data               0
casos              0
casos_novos        0
casos_pc           0
casos_mm7d         0
obitos             0
obitos_novos       0
obitos_pc          0
obitos_mm7d        0
letalidade         0
nome_drs         952
cod_drs            0
pop                0
semana_epidem      0
dtype: int64

In [ ]:
# EXCLUIR TODOS OS VALORES MISSING
covid_sp2 = covid_sp.dropna()

In [ ]:
covid_sp2.isnull().sum()

municipio        0
codigo_ibge      0
data             0
casos            0
casos_novos      0
casos_pc         0
casos_mm7d       0
obitos           0
obitos_novos     0
obitos_pc        0
obitos_mm7d      0
letalidade       0
nome_drs         0
cod_drs          0
pop              0
semana_epidem    0
dtype: int64

In [ ]:
# SUBSTITUIR OS VALORES MISSING PELA MEDIANA
covid_sp['obitos_novos'].fillna(covid_sp['obitos_novos'].median(), inplace=True)

In [ ]:
# SUBSTITUIR OS VALORES MISSING PELA MÉDIA
covid_sp['obitos_novos'].fillna(covid_sp['obitos_novos'].mean(), inplace=True)

In [ ]:
# SUBSTITUIR OS VALORES MISSING POR QUALQUER OUTRO VALOR
covid_sp['obitos_novos'].fillna(10, inplace=True)

### **Classificação e alteração da tipagem dos atributos**

Análise dos tipos de atributos:

object: strings

int64: inteiros

float64: reais

complex: complexos

In [ ]:
covid_sp_alterado.dtypes

municipio         object
data              object
casos              int64
casos_pc          object
casos_mm7d        object
obitos             int64
obitos_novos       int64
obitos_mm7d       object
letalidade        object
semana_epidem      int64
total              int64
indice           float64
dtype: object

## **Salvando (Exportando) o Dataframe Tratado**

In [ ]:
covid_sp_alterado.to_csv('covid_sp_tratado.csv', sep=';', encoding='utf-8', index = False)