# segundo bimestre Python

# **Listas:**
As listas são usadas para armazenar vários itens em uma única variável.

São um dos 4 tipos de dados integrados em Python usados para armazenar coleções de dados

As listas são criadas usando colchetes:
my_list=["apple","banana","cherry"]

-os itens das listas são oredenados,alteráveis e permite valores duplicados

-os itens da lista são indexados,o primeiro tem um index[0],o segundo tem um index[1] etc..

-------------------------------------------------------------------------------
-Para descobrir o tipo de variável que temos na lista temos que usar o "type"

-foi utilizador o "type(mylist[0]) para descobrir o tipo de variável da posição 0

In [ ]:
mylist=["apple","banana","cherry"]
type(mylist[0])

str

para printar todos elementos da lista

In [ ]:
mylist=["apple","banana","Cherry","melon","orange"]
for i in range (len(mylist)):
  print(mylist[0:4])

['apple', 'banana', 'Cherry', 'melon']
['apple', 'banana', 'Cherry', 'melon']
['apple', 'banana', 'Cherry', 'melon']
['apple', 'banana', 'Cherry', 'melon']
['apple', 'banana', 'Cherry', 'melon']

Quando coloca número negativo(-2) ele pega a lista ao contrário

In [ ]:
mylist=["apple","banana","Cherry","melon","orange"]
print(mylist[-2:5])

['melon', 'orange']

Para alterar a lista:

In [ ]:
mylist=["apple","banana","Cherry","melon","orange"]
print(mylist)
mylist[3]="watermelon"
print(mylist)

['apple', 'banana', 'Cherry', 'melon', 'orange']
['apple', 'banana', 'Cherry', 'watermelon', 'orange']

exemplos de alteração da lista:

In [ ]:
mylist=["apple","banana","Cherry","melon","orange"]
print(mylist)
mylist.insert(3,"watermelon")
print(mylist)
mylist.append("fruta2")
print(mylist)

['apple', 'banana', 'Cherry', 'melon', 'orange']
['apple', 'banana', 'Cherry', 'watermelon', 'melon', 'orange']
['apple', 'banana', 'Cherry', 'watermelon', 'melon', 'orange', 'fruta2']

# **Exercícios:**
**1)Crie uma lista vazia chamada "nomes", adicione os nomes "Alice", "Bob" e "Carol" à lista e imprima a lista resultante**

In [ ]:
nomes = []  # cria uma lista vazia chamada "nomes"
nomes.append("Alice")  # adiciona "Alice" à lista
nomes.append("Bob")  # adiciona "Bob" à lista
nomes.append("Carol")  # adiciona "Carol" à lista
print(nomes)  # imprime a lista resultante

['Alice', 'Bob', 'Carol']

**2)Crie uma lista chamada "numeros" com os números de 1 a 10 e imprima os números pares.**

In [ ]:
numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  # cria a lista "numeros"
pares = []  # cria uma lista vazia para armazenar os números pares
for numero in numeros:  # para cada número na lista "numeros"
    if numero % 2 == 0:  # se o número for par
        pares.append(numero)  # adiciona o número à lista de pares
print(pares)  # imprime a lista de pares

[2, 4, 6, 8, 10]

**3)Crie uma lista chamada "frutas" com as frutas "maçã", "banana", "laranja" e "uva". Em seguida, remova a "laranja" da lista e imprima a lista resultante.**

In [ ]:
frutas=["maça","banana","laranja","uva"]#cria uma lista "frutas"
frutas.remove("laranja")#remove "laranja"
print(frutas)#imprime a lista sem "laranja"

['maça', 'banana', 'uva']

**4)Crie uma lista chamada "notas" com as notas 7, 8, 9 e 10. Calcule a média das notas e imprima o resultado.**

In [ ]:
notas = [7, 8, 9, 10]  # cria a lista "notas"
soma = sum(notas)  # soma as notas usando a função "sum"
media = soma / len(notas)  # calcula a média dividindo a soma pelo número de notas
print("A média das notas é:", media)  # imprime o resultado

A média das notas é: 8.5

**5)Crie uma lista chamada "compras" com os itens "leite", "pão", "arroz" e "feijão". Em seguida, ordene a lista em ordem alfabética e imprima a lista resultante.**

In [ ]:
compras = ["leite", "pão", "arroz", "feijão"]  # cria a lista "compras"
compras.sort()  # ordena a lista em ordem alfabética
print(compras)  # imprime a lista resultante

['arroz', 'feijão', 'leite', 'pão']

6)Escreva uma função que receba uma lista de números como parâmetro e retorne uma nova lista contendo apenas os números pares.
**negrito**

In [ ]:
lista_numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  # cria uma lista de números
pares = [numero for numero in lista_numeros if numero % 2 == 0]  # usa list comprehension para criar uma nova lista contendo apenas os números pares
print(pares)  # imprime a lista de números pares

[2, 4, 6, 8, 10]

**ou podemos fazer assim:**

In [ ]:
def numeros_pares(lista):
    pares = []  # cria uma lista vazia para armazenar os números pares
    for numero in lista:  # para cada número na lista recebida como parâmetro
        if numero % 2 == 0:  # se o número for par
            pares.append(numero)  # adiciona o número à lista de pares
    return pares  # retorna a lista de pares
lista_numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  # cria uma lista de números
pares = numeros_pares(lista_numeros)  # chama a função "numeros_pares" para obter a lista de números pares
print(pares)  # imprime a lista de números pares

[2, 4, 6, 8, 10]

**7)Escreva uma função que receba uma lista de palavras como parâmetro e retorne uma nova lista contendo apenas as palavras com mais de 5 letras.**

In [ ]:
def palavras_mais_5_letras(lista_palavras):
    mais_5_letras = []  # cria uma lista vazia para armazenar as palavras com mais de 5 letras
    for palavra in lista_palavras:  # para cada palavra na lista recebida como parâmetro
        if len(palavra) > 5:  # se a palavra tiver mais de 5 letras
            mais_5_letras.append(palavra)  # adiciona a palavra à lista de palavras com mais de 5 letras
    return mais_5_letras  # retorna a lista de palavras com mais de 5 letras
    
lista_palavras = ["gato", "cachorro", "papagaio", "leão", "elefante", "girafa"]  # cria uma lista de palavras
mais_5_letras = palavras_mais_5_letras(lista_palavras)  # chama a função "palavras_mais_5_letras" para obter a lista de palavras com mais de 5 letras
print(mais_5_letras)  # imprime a lista de palavras com mais de 5 letras

['cachorro', 'papagaio', 'elefante', 'girafa']

**8)Escreva uma função que receba duas listas como parâmetros e retorne uma nova lista contendo os elementos que estão presentes em ambas as listas.**

In [ ]:
def elementos_comuns(lista1, lista2):
    comuns = []  # cria uma lista vazia para armazenar os elementos comuns
    for elemento in lista1:  # para cada elemento na primeira lista
        if elemento in lista2 and elemento not in comuns:  # se o elemento também estiver na segunda lista e ainda não estiver na lista de comuns
            comuns.append(elemento)  # adiciona o elemento à lista de comuns
    return comuns  # retorna a lista de elementos comuns

lista1 = [1, 2, 3, 4, 5]  # cria a primeira lista
lista2 = [3, 4, 5, 6, 7]  # cria a segunda lista
comuns = elementos_comuns(lista1, lista2)  # chama a função "elementos_comuns" para obter a lista de elementos comuns
print(comuns)  # imprime a lista de elementos comuns

[3, 4, 5]

# **Dicionário**

Os dicionários são usados ​​para armazenar valores de dados em pares chave:valor.

Um dicionário é uma coleção que é ordenada*, modificável e não permite duplicatas.

In [ ]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

## Itens do Dicionário
Os itens do dicionário são ordenados, alteráveis ​​e não permitem duplicatas.

Os itens do dicionário são apresentados em pares chave:valor e podem ser referidos usando o nome da chave.

In [ ]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict["brand"])

Ford

## Duplicatas não permitidas

In [ ]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964,
  "year": 2020
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 2020}

##Tamanho do Dicionário
Para determinar quantos itens um dicionário possui, use a len()função:

In [ ]:
print(len(thisdict))

## Itens do Dicionário - Tipos de Dados
Os valores nos itens do dicionário podem ser de qualquer tipo de dados:

In [ ]:
thisdict = {
  "brand": "Ford",
  "electric": False,
  "year": 1964,
  "colors": ["red", "white", "blue"]
}
print(thisdict)

{'brand': 'Ford', 'electric': False, 'year': 1964, 'colors': ['red', 'white', 'blue']}

## Tipo
Da perspectiva do Python, os dicionários são definidos como objetos com o tipo de dados 'dict':

In [ ]:
print(type(thisdict))

#exercicio

In [ ]:
pessoa1={
    "nome":"Molina",
    "idade": 38,
    "emails" : {
        "proffisional": "molina@ceub",
        "pessoal": "aaa@gmail.com"
  }
}

print(pessoa1)

{'nome': 'Molina', 'idade': 38, 'emails': {'proffisional': 'molina@ceub', 'pessoal': 'aaa@gmail.com'}}

## O Construtor dict()
Também é possível usar o construtor dict() para criar um dicionário

In [ ]:
thisdict = dict(name = "John", age = 36, country = "Norway")
print(thisdict)

## Acessando Itens
Você pode acessar os itens de um dicionário referindo-se ao seu nome de chave, entre colchetes ou existe também um método chamado get()que lhe dará o mesmo resultado:

In [ ]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
x = thisdict["model"]
print(x)

Mustang

In [ ]:
x = thisdict.get("model")
print(x)

Mustang

## Obter valores
O values()método retornará uma lista de todos os valores do dicionário.

In [ ]:
x = thisdict.values()
print(x)

dict_values(['Ford', 'Mustang', 1964])

## Obter itens
O items()método retornará cada item em um dicionário, como tuplas em uma lista.

In [ ]:
x = thisdict.items()
print(x)

dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964)])

## Python - Alterar itens do dicionário

In [ ]:
#pra alterar o item 
thisdict["model"] = "Ka"
print(thisdict)

#pra acrescentar um item
thisdict["color"]="red"
print(thisdict)

{'brand': 'Ford', 'model': 'Ka', 'year': 1964}
{'brand': 'Ford', 'model': 'Ka', 'year': 1964, 'color': 'red'}

#Métodos aplicados a Dicionário

copy() -> Returns a copy of the dictionary

In [ ]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

x = car.copy()

print(x)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

fromkeys() ->	Returns a dictionary with the specified keys and value

In [ ]:
#criando um dicionário com 3 chaves e valores iguais a 0
x = ('key1', 'key2', 'key3')
y = 0

thisdict = dict.fromkeys(x, y)

print(thisdict)

{'key1': 0, 'key2': 0, 'key3': 0}

get()	-> Returns the value of the specified key

In [ ]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

x = car.get("model")

print(x)

items() ->	Returns a list containing a tuple for each key value pair

In [ ]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

x = car.items()
#print(x)

for i in car.items():
  print(i)

('brand', 'Ford')
('model', 'Mustang')
('year', 1964)

keys()-> Returns a list containing the dictionary's keys

In [ ]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

x = car.keys()

print(x)

dict_keys(['brand', 'model', 'year'])

pop()	-> Removes the element with the specified key

In [ ]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

car.pop("model")

print(car)

{'brand': 'Ford', 'year': 1964}

popitem()	-> Removes the last inserted key-value pair

In [ ]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

car.popitem()

print(car)

{'brand': 'Ford', 'model': 'Mustang'}

update()	-> Updates the dictionary with the specified key-value pairs

In [ ]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

car.update({"color": "White"})

print(car)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'White'}

values()	-> Returns a list of all the values in the dictionary

In [ ]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

x = car.values()

print(x)

dict_values(['Ford', 'Mustang', 1964])

clear() -> Removes all the elements from the dictionary

In [ ]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

car.clear()

print(car)

{}

# **DADOS**

In [ ]:
# importando as bibliotecas
# pandas - biblioteca responsável por manipular os dados
import numpy as np
import pandas as pd

In [ ]:
# criando uma série
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [ ]:
# criando um dataframe a partir de um array do numpy
dates = pd.date_range("20130101", periods=6)

dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))

df

                   A         B         C         D
2013-01-01 -0.147093 -0.239431 -1.333389  0.062334
2013-01-02 -0.058048 -1.603651  1.345783 -0.965372
2013-01-03  0.035064  0.014955 -1.239167  0.179087
2013-01-04  0.283164 -1.945868  0.067915  1.387462
2013-01-05  1.589506  1.768059  0.593643  0.709782
2013-01-06  0.207859 -0.702195  0.115407  0.843082

In [ ]:
# criando um data frame a partir de um dicionário
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)


df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [ ]:
# verificar os tipos dos dados
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [ ]:
# vendo os dados
df2.head()

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [ ]:
# vendo os indices (linhas)
df2.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [ ]:
# vendo os cabeçalhos (colunas)
df2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [ ]:
# mostra uma estátisca sumarizada dos dados 
df2.describe()

         A    C    D
count  4.0  4.0  4.0
mean   1.0  1.0  3.0
std    0.0  0.0  0.0
min    1.0  1.0  3.0
25%    1.0  1.0  3.0
50%    1.0  1.0  3.0
75%    1.0  1.0  3.0
max    1.0  1.0  3.0

In [ ]:
# transpondo os dados (compare com a original)
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.147093   -0.058048    0.035064    0.283164    1.589506    0.207859
B   -0.239431   -1.603651    0.014955   -1.945868    1.768059   -0.702195
C   -1.333389    1.345783   -1.239167    0.067915    0.593643    0.115407
D    0.062334   -0.965372    0.179087    1.387462    0.709782    0.843082

In [ ]:
df

                   A         B         C         D
2013-01-01 -0.147093 -0.239431 -1.333389  0.062334
2013-01-02 -0.058048 -1.603651  1.345783 -0.965372
2013-01-03  0.035064  0.014955 -1.239167  0.179087
2013-01-04  0.283164 -1.945868  0.067915  1.387462
2013-01-05  1.589506  1.768059  0.593643  0.709782
2013-01-06  0.207859 -0.702195  0.115407  0.843082

In [ ]:
# selecionado uma coluna
df['A']

In [ ]:
# selecionando um intervalo de linhas
df[0:3]

In [ ]:
# selecionando um intervalo de linhas
df["20130102":"20130104"]

In [ ]:
# selecionando por posição
df.iloc[3]

In [ ]:
# selecionando por intervalo de posições (linha : coluna)
df.iloc[3:5, 0:2]

# **PROJETO ANÁLISE DOS DADOS DO COVID 19 NO ESTADO DE SÃO PAULO**

### **Importação de arquivo csv**

In [ ]:
# comando do google colab para integração com o google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# carregando as informações do arquivo csv
covid_sp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dados/dados_covid_sp.csv', 
                       sep=';', encoding='utf-8')
# encoding: codificação de caracteres, normalmente utiliza-se 
#o iso-8859-1, utf-8, latin-1)

In [ ]:
# visualizando o dados
covid_sp.head()

,nome_munic,codigo_ibge,datahora,casos,casos_novos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_pc,obitos_mm7d,letalidade,nome_drs,cod_drs,pop,semana_epidem
0,Adamantina,3500105,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",Marília,5,33894,9
1,Adolfo,3500204,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",São José do Rio Preto,15,3447,9
2,Aguaí,3500303,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",São João da Boa Vista,14,35608,9
3,Águas da Prata,3500402,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",São João da Boa Vista,14,7797,9
4,Águas de Lindóia,3500501,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",Campinas,3,18374,9

In [ ]:
# contando as linhas e colunas
covid_sp.shape

(614992, 16)

### **Importação de arquivo Excel**

In [ ]:
# carregando informações de um arquivo xlsx
covid_sp2 = pd.read_excel('/content/drive/MyDrive/20231/dados/dados_covid_sp2.xlsx')

In [ ]:
# visualizando os dados
covid_sp2.head()

In [ ]:
# contanto as linhas e coluna
covid_sp2.shape

### **Importação através de uma url**

In [ ]:
# carregando informações de dados a partir de uma url
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

In [ ]:
# criando um array para definir os nomes das colunas
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

In [ ]:
iris = pd.read_csv(url, names=colnames)

In [ ]:
# mostrando todas as colunas do dataframe
iris.columns

In [ ]:
iris.head(10)

   sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [ ]:
# verificando o tipo de dado que está sendo utilizado
type(iris)

pandas.core.frame.DataFrame

In [ ]:
iris.shape

(150, 5)

In [ ]:
# contanto o número de linhas
len(iris.Class)

150

In [ ]:
# acessando uma informação específica
iris['sepal-width'][0]
iris['sepal-width'][2]

3.2

### **Datasets das bibliotecas do Python**

https://www.statsmodels.org/stable/datasets/index.html

In [ ]:
# biblioteca de dados para treino do python
import statsmodels.api as sm

In [ ]:
cancer = sm.datasets.cancer.load_pandas().data
cancer.head()

   cancer  population
0     1.0       445.0
1     0.0       559.0
2     3.0       677.0
3     4.0       681.0
4     3.0       746.0

In [ ]:
type(cancer)

pandas.core.frame.DataFrame

In [ ]:
cancer.shape

(301, 2)

https://scikit-learn.org/stable/datasets/toy_dataset.html

In [ ]:
import sklearn

In [ ]:
from sklearn import datasets

In [ ]:
iris = datasets.load_iris()
iris

In [ ]:
iris.data

## **Organização dos dados**

### **Renomeando variáveis (colunas)**

In [ ]:
covid_sp.head(3)

,nome_munic,codigo_ibge,datahora,casos,casos_novos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_pc,obitos_mm7d,letalidade,nome_drs,cod_drs,pop,semana_epidem
0,Adamantina,3500105,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",Marília,5,33894,9
1,Adolfo,3500204,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",São José do Rio Preto,15,3447,9
2,Aguaí,3500303,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",São João da Boa Vista,14,35608,9

In [ ]:
covid_sp.head(3)

,nome_munic,codigo_ibge,datahora,casos,casos_novos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_pc,obitos_mm7d,letalidade,nome_drs,cod_drs,pop,semana_epidem
0,Adamantina,3500105,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",Marília,5,33894,9
1,Adolfo,3500204,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",São José do Rio Preto,15,3447,9
2,Aguaí,3500303,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",São João da Boa Vista,14,35608,9

In [ ]:
covid_sp.head(3)

,nome_munic,codigo_ibge,datahora,casos,casos_novos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_pc,obitos_mm7d,letalidade,nome_drs,cod_drs,pop,semana_epidem
0,Adamantina,3500105,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",Marília,5,33894,9
1,Adolfo,3500204,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",São José do Rio Preto,15,3447,9
2,Aguaí,3500303,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",São João da Boa Vista,14,35608,9

In [ ]:
covid_sp.rename(columns={'datahora': 'data'}, inplace=True)

In [ ]:
covid_sp.head(3)

,nome_munic,codigo_ibge,data,casos,casos_novos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_pc,obitos_mm7d,letalidade,nome_drs,cod_drs,pop,semana_epidem
0,Adamantina,3500105,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",Marília,5,33894,9
1,Adolfo,3500204,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",São José do Rio Preto,15,3447,9
2,Aguaí,3500303,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",São João da Boa Vista,14,35608,9

In [ ]:
covid_sp.columns

Index(['nome_munic', 'codigo_ibge', 'data', 'casos', 'casos_novos', 'casos_pc',
       'casos_mm7d', 'obitos', 'obitos_novos', 'obitos_pc', 'obitos_mm7d',
       'letalidade', 'nome_drs', 'cod_drs', 'pop', 'semana_epidem'],
      dtype='object')

### **Excluindo variáveis (colunas)**

In [ ]:
# Excluir por nome
covid_sp_alterado = covid_sp.drop(columns=['casos_novos'])

In [ ]:
covid_sp_alterado.head(2)

,nome_munic,codigo_ibge,data,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_pc,obitos_mm7d,letalidade,nome_drs,cod_drs,pop,semana_epidem
0,Adamantina,3500105,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",Marília,5,33894,9
1,Adolfo,3500204,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,00000000000000e+00","0,000000000000000","0,000000000000000000",São José do Rio Preto,15,3447,9

In [ ]:
covid_sp_alterado.shape

(614992, 15)

In [ ]:
# Excluir por número (axis = 1 irá excluir a coluna)
covid_sp_alterado = covid_sp_alterado.drop(covid_sp_alterado.columns[[1]],axis=1)

In [ ]:
# Excluir mais de uma variável (inplace = True altera a lista sem a necessida de realizar a atribuição novamante)
covid_sp_alterado.drop(columns=['obitos_pc','cod_drs'],inplace=True)

In [ ]:
covid_sp_alterado.head()

,nome_munic,data,casos,casos_pc,casos_mm7d,obitos,obitos_novos,obitos_mm7d,letalidade,nome_drs,pop,semana_epidem
0,Adamantina,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",Marília,33894,9
1,Adolfo,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",São José do Rio Preto,3447,9
2,Aguaí,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",São João da Boa Vista,35608,9
3,Águas da Prata,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",São João da Boa Vista,7797,9
4,Águas de Lindóia,2020-02-25,0,"0,00000000000000e+00","0,000000000000000",0,0,"0,000000000000000","0,000000000000000000",Campinas,18374,9

In [ ]:
covid_sp_alterado.drop(covid_sp_alterado.columns[[9,10]],axis=1, inplace=True)

In [ ]:
covid_sp_alterado.shape

(614992, 10)

### **Criando e alterando valores das colunas (Variáveis)**